# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2ddd23da16079b805fc35ad7927b7e9cf490c4e96780ac36bb0910b29036aea9f261535a20ec21a39892c368f68820659a92973fd70e6a9f8b6e5af4216c48b

test:
  secret_key_base: 7731e5cbb9cc693dfc1f1014a7c6969d4f7bdfcd4456acaa9d5b5eaed757e7cad8cc19d69bd26a4e9a4a63c3312e954c82a4caaf0b35c7a29a2d75346f6ce36b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
